{
 "title": "CPU",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_response_time_seconds_count{namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (None Percentage)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s])) by (container_label_io_kubernetes_pod_name) / 0.5 * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s])) by (container_label_io_kubernetes_pod_name) / 0.5 * 100  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s])) by (container_label_io_kubernetes_pod_name) / 16 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_cpu_user_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_cpu_usage_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_cpu_system_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_cpu_cfs_throttled_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_cpu_cfs_throttled_periods_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_cpu_cfs_periods_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_periods_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_spec_cpu_quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_spec_cpu_period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_period{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_cpu_load_average_10s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_spec_cpu_shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}