{
 "title": "FileSystem",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "container_fs_io_time_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_io_time_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_io_time_weighted_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_io_time_weighted_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_sector_writes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_sector_writes_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_write_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_write_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_writes_merged_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_merged_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_writes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_io_current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_inodes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(container_fs_inodes_total{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_io_current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(container_fs_io_current{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_inodes_free",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(container_fs_inodes_free{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_read_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_read_seconds_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_reads_merged_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_merged_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_sector_reads_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_sector_reads_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_fs_reads_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}