{
 "title": "Memory",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_response_time_seconds_count{namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_failures_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_rss",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_working_set_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_max_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(container_memory_cache{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_mapped_file",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(container_memory_mapped_file{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_failcnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_failcnt{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_spec_memory_limit_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_spec_memory_swap_limit_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(container_spec_memory_swap_limit_bytes{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_spec_memory_reservation_limit_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_memory_swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum(container_memory_swap{container_label_io_kubernetes_pod_namespace=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}