{
 "title": "Network",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_response_time_seconds_count{namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_receive_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_transmit_packets_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_transmit_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_receive_packets_dropped_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_receive_errors_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_transmit_packets_dropped_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_receive_packets_dropped_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_receive_packets_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_errors_total{container_label_io_kubernetes_pod_namespace=\"demo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}