---
apiVersion: v1
kind: Service
metadata:
  name: predictapp
  namespace: demo
  labels:
    app: predictapp
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app: predictapp
