---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predictapp
  namespace: demo
  labels:
    team: devops
spec:
  endpoints:
  - port: http
    interval: 5s
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app: predictapp
