---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: lstm
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Pods
    pods:
      metric:
        # use the metric that you used above: pods/http_requests
        name: future_pod_cpu_usage
      target:
        type: AverageValue
        averageValue: 200m
